### ISSUE TITLE
Use XAudioJS for audio output support

### ISSUE THREAD

**Issue by ghost** [fasterthanlime/jsmad#15]
I wrote an audio library at https://github.com/grantgalitz/XAudioJS that provides support for audio output in JS via mozilla audio and webkit web audio. It has a fallback of using flash player if these APIs are not supported. The thing that struck me was that you guys are saying you can't resample for web audio, which my library does do (It resamples in JS). It's a basic thin abstraction of the various methods of outputting audio and I spent a lot of time developing it when originally creating it for my JS GameBoy Color emulator. I thought you guys might want to look at it or use it. :)

**Comment by nddrylliog** [comment]
Hi grantgalitz! Thanks for the information :)

Actually, it's not that we can't, it's more than we won't. audiolib.js, the audio library we're using for jsmad, _does_ resampling, but doing it would let Google get away with this bug: http://code.google.com/p/chromium/issues/detail?id=86767

It seems XAudioJS is very similar to audiolib.js. Did you know about it? What are the differences between those?

**Comment by ghost** [comment]
I silently resample with a nearest-neighbor audio resampling algorithm for performance anyhow, because I needed to do so to get the 70 khz audio running perfectly in all browsers. It doesn't take a lot of CPU at least for me to resample anyhow. I support mozilla audio and web audio, and a flash fallback for when neither of these are supported. The API you program to is the same for all these APIs, since it's thin abstracted around each one. You can specify an underrun callback and even push audio into the buffer to get the best of both worlds (passive callback and block writing). You can specify the buffer constraints for min and max buffering as well. I wish the author of audiolib could talk to me so we could possibly merge the two or share tips at least.

**Comment by jussi-kalliokoski** [comment]
Hello Grant!

I've been meaning to contact you for some time now.

audiolib.js uses a linear interpolation algorithm to do the resampling, which is a bit nicer, but also a bit slower. Maybe we both should implement both? :)

audiolib.js also supports both underrun callback's and buffer writes, and actually simultaneously, mixing them.

I've been trying to write an audio element-based fallback for the audio APIs (the flash things give so suboptimal performance that I don't want to use them) and I see that in your code there's something like that, care to share what's happening there? I'd be happy to contribute to XAudioJS in return. ;)

But yes, like said, I don't want to do the resampling in JS, I want them to make a proper API. :)

By the way, your JS GBC, very nice!

**Comment by jussi-kalliokoski** [comment]
Oh, and here's the link to the bug report on your initiative, Grant, http://code.google.com/p/chromium/issues/detail?id=73062 , I think it would be good to have your voice there as well.

**Comment by ghost** [comment]
I did another fallback other than the flash fallback as well, it's a WAV PCM data URI realtime generator. I only use it if flash isn't supported and we've already hit the flash fallback, since it's worse to use than the flash fallback (Pretty much impossible to  be gapless when the API is generating one data URI after the other) and all webkit browsers leak WAV PCM data URIs. As for the resampling algorithms, I could add a heuristic to know when to use the gaussian/interpolation algorithm and when to use my faster and slightly less accurate resampling algorithms. As for doing resampling in JS overall, I don't do it unless I have to, in other words I check to see if an API can do it first or if it even needs to be done before resampling at all. If crogers is going to implement resampling in his API, then I'd assume we could feature test for resampling support (Like a resampling node or something could be added?), and only then if resampling in the API is not found, then we can do it in JS silently. My XAudioJS lib is not as elegant as yours,  I just made mine to be fast and to be as close to the metal as possible (I don't do crazy stuff, I purposefully made it an output lib that just outputs audio, no effects). With my library in general I expose the buffering left, and I resample as close to output as possible, for flash for instance I resample it inside the flash swf itself that I wrote.

I'm wondering if we could combine our efforts somehow.

**Comment by ghost** [comment]
Also, are you experiencing any web audio bugs on linux and windows? I know firefox has bugs on linux and overbuffering on Windows XP.

**Comment by ghost** [comment]
I'll close this to not annoy jsmad users with an open issue ticket.

**Comment by ghost** [comment]
I'll look at the bug report crogers opened, I guess I forgot about it. :/

**Comment by jussi-kalliokoski** [comment]
> I did another fallback other than the flash fallback as well, it's a WAV PCM data URI realtime generator. I only use it if flash isn't supported and we've already hit the flash fallback, since it's worse to use than the flash fallback

Yes I fear that too, and even the flash things are unacceptably unstable for my flavour, I'll probably drop the idea, and keep using PCM Decoding / Encoding only for recording and sample loading purposes.

> Like a resampling node or something could be added?

What are your opinions of my suggestion on the bug I linked?

> Also, are you experiencing any web audio bugs on linux and windows? I know firefox has bugs on linux and overbuffering on Windows XP.

I know of this web audio bug: http://code.google.com/p/chromium/issues/detail?id=82795 , it can be worked around by deferring the creation of the audio context at least two seconds from the onload event. Basically, when DOM stuff happens, there's a chance that Web Audio API hangs and starts repeating the last buffer it got.

Also, there's the background processing bug https://bugzilla.mozilla.org/show_bug.cgi?id=665000 where Firefox slows down timers in background tabs to have a 1000ms interval, but it can be worked around either with Audio Workers, where possible, putting the timers inside workers with a blob url in Fx6+, but in Fx5, the best bet is that if you need background processing, use postMessage instead of timeouts, but that's very costly. Here's relevant code from audiolib.js https://github.com/jussi-kalliokoski/audiolib.js/blob/master/js/io/audiodevice.js#L141 I added a flag, so that the hack comes to use only if the user decides so, because it's a kinda intrusive and performance-affecting hack.

We should go through each other's code to see if there are problems we've fixed in our own code and if there are problems in our own code that the other one has solved.
